Prevent 23 page
scanabc/scanabc.github.io pull request #20
Opened 2022-12-14 10:47 UTC by nkapu

2022-12-15 12:01 UTC, hkortti requested changes
Muutosehdotukset inlinenä, niiden lisäksi .DS_Store hakkarit pois vendor- ja bootstrap-kansioiden alta (ja muualtakin jos on lipsahtanut).

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +          Lämmittelemme Disobeyn puheenvuoroihin Maria01:n tiloissa -
```suggestion
          Lämmittelemme porukkaa ennen Disobeytä Maria01:n tiloissa -
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +          uusia tuotejulkistuksia sekä muuta tietoturvateemaista
```suggestion
          tarinoita perustajilta, tuotejulkistuksia, sekä muuta tietoturvateemaista 
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>9:30-9:40 - Tervetuloa</p>
```suggestion
       
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>9:40-10:00 - Tomi Tuominen</p>
```suggestion
        <p>9:30-10:00 - Tomi Tuominen - Securing Wolt</p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>10:00-10:20 <a href="https://badrap.io/" target="_blank" rel="noopener">Badrap</a>  - Jani Kenttälä </p>
```suggestion
        <p>10:00-10:20 Jani, Heikki ja Jukke - <a href="https://badrap.io/" target="_blank" rel="noopener">Badrap</a></p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>10:20-10:40 <a href="https://sensorfleet.com/" target="_blank" rel="noopener">SensorFleet</a>  - Sami Petäjäsoja </p>
```suggestion
        <p>10:20-10:40 Sami Petäjäsoja - <a href="https://sensorfleet.com/" target="_blank" rel="noopener">SensorFleet</a></p>
        <p>TAUKO</p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>10:40-11:00 <a href="https://sensorfu.com/" target="_blank" rel="noopener">SensorFu</a>  - Mikko Kenttälä </p>
```suggestion
        <p>11:00-11:20 Mikko Kenttälä - <a href="https://sensorfu.com/" target="_blank" rel="noopener">SensorFu</a></p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>11:00-11:20 <a href="https://signet.app/" target="_blank" rel="noopener">Signet</a> </p>
```suggestion
        <p>11:20-11:40 <a href="https://signet.app/" target="_blank" rel="noopener">Signet</a> </p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>11:20-11:40 <a href="https://xiphera.com/" target="_blank" rel="noopener">Xiphera</a>  - Matti Tommiska </p>
```suggestion
        <p>11:40-12:00 Matti Tommiska - <a href="https://xiphera.com/" target="_blank" rel="noopener">Xiphera</a></p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>11:40-12:30 Vapaata jutustelua ja siirtyminen Disobeyhin</p>
```suggestion
        <p>12:00-12:30 Vapaata jutustelua ja siirtyminen Disobeyhin</p>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +         <a href="https://tinyurl.com/abcprevent20" target="_blank" rel="noopener" class="signup">https://tinyurl.com/abcprevent20</a>
```suggestion
         <a href="https://tinyurl.com/abcprevent23" target="_blank" rel="noopener" class="signup">https://tinyurl.com/abcprevent23</a>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +        <p>Tapahtuma järjestetään Maria01:n Lars Sonck Venuessa. Kävele Building 3:n <a href="https://maria.io/campus/buildings/" target="_blank" rel="noopener">(Building 3)</a>.
```suggestion
        <p>Tapahtuma järjestetään Maria01:n rakennuksessa 3, Lars Sonck Venuessa. Kävele <a href="https://maria.io/campus/buildings/" target="_blank" rel="noopener">Building 3</a>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +  <meta name="description" content="Haastoimme yritykset antamaan tilannepäivitykset demojen avulla. 14.2. klo 10:00 - 11:30 Lapinlahdenkatu 16, Helsinki">
```suggestion
  <meta name="description" content="Prevent23 tarjoaa tietoturvakeskustelua ennen Disobeytä. 17.2.2023 klo 9-12:30 Maria01, Lapinlahdenkatu 16, Helsinki">
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +  <meta property="og:url" content="http://www.scanabc.com/prevent20/" />
```suggestion
  <meta property="og:url" content="http://www.scanabc.com/prevent23/" />
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +  <meta property="og:description" content="Haastoimme yritykset antamaan tilannepäivitykset demojen avulla. 14.2. klo 10:00 - 11:30 Lapinlahdenkatu 16, Helsinki." />
```suggestion
  <meta property="og:description" content="Prevent23 tarjoaa tietoturvakeskustelua ennen Disobeytä. 17.2.2023 klo 9-12:30 Maria01, Lapinlahdenkatu 16, Helsinki" />
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +  <meta property="og:image" content="http://www.scanabc.com/prevent20/img/social-opengraph.jpg"/>
```suggestion
  <meta property="og:image" content="http://www.scanabc.com/prevent23/img/social-opengraph.jpg"/>
```

2022-12-15 12:01 UTC, hkortti commented on prevent23/index.html
> +         <p><strong>Aika:</strong> pe 17.2.2023 klo 9-12</p>
```suggestion
         <p><strong>Aika:</strong> pe 17.2.2023 klo 9-12:30</p>
```

2022-12-16 14:14 UTC, nkapu commented on prevent23/index.html
> +         <p><strong>Aika:</strong> pe 17.2.2023 klo 9-12</p>
Resolved in update schedule and metadata commit

2022-12-16 14:15 UTC, nkapu commented on prevent23/index.html
> +  <meta property="og:description" content="Haastoimme yritykset antamaan tilannepäivitykset demojen avulla. 14.2. klo 10:00 - 11:30 Lapinlahdenkatu 16, Helsinki." />
Resolved in update schedule and metadata commit

2022-12-16 14:15 UTC, nkapu commented on prevent23/index.html
> +  <meta property="og:url" content="http://www.scanabc.com/prevent20/" />
Resolved in update schedule and metadata commit

2022-12-16 14:15 UTC, nkapu commented on prevent23/index.html
> +          uusia tuotejulkistuksia sekä muuta tietoturvateemaista
Resolved in update schedule and metadata commit

2022-12-19 08:00 UTC, merged